[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tipjar = "4E55dXLQkqXn7zi75aeBh4LJMXeAZw4KPYwgijuSCjun"


[programs.devnet]
tipjar = "4E55dXLQkqXn7zi75aeBh4LJMXeAZw4KPYwgijuSCjun"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"



[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
initialize = "ts-node scripts/initialize.ts"
